### ISSUE TITLE
server error is reproduced in house creation

### ISSUE THREAD

**Issue by Norbbs** [fjborquez/katara#24]
**As a** Data ower
**I want to** fix a bug when i tried to create a house
**So that** I can follow the flow successful

### Definition Of Ready (DoR)
|   | **Definition**                                   |  **Observations**  |
|---|----------------------------------------------|---|
|  <ul><li>- [x] </li></ul> | Story where the bug was identified or an easy way to reproduce                                            |   |
|  <ul><li>- [x] </li></ul> | Environment (Dev, Test, prod)                                                    |   |
|  <ul><li>- [x] </li></ul> | Severity (Low, Medium, High)                                                    |   |

### Bug Description
The following flows reproduce errors in the house creation

![Image](https://github.com/fjborquez/katara/assets/5569594/16a99b8b-f734-4358-bd20-f5f1a546c74b)

### Expected Behavior
House added

### Actual Behavior
Server error

### Impact
Can't create new houses

**Comment by fjborquez** [comment]
The city with ID 3 didn't exists and Aang could not generate the relationship.
The city was aggregated with "Concepcion" as description.
Please @Norbbs  , check it.
