### ISSUE TITLE
Add an icon column to visualize the status of each inventory item

### ISSUE THREAD

**Issue by Norbbs** [fjborquez/katara#46]
**As a** User
**I want to** see an icon bound to the status in the inventory table
**So that** I can quickly and visually assess the availability and condition of each item in the inventory, improving my ability to manage stock effectively.

### Scope
> 1. Add a column with an icon for each item status
> 2. ⚠️ for Approaching Expiry
> 3. ✅ for fresh status
> 4. 🚨 for expired statys
> 5. ❓ for undefined
> 6. When the user hovers the mouse over each icon, a message with the status description can be displayed. 

### Out of scope
> 1. any other columns 

### Result (Example)
![Image](https://github.com/user-attachments/assets/d72c389c-ff0a-4fb0-a2ab-88adc6c1ce3e)

**Comment by Norbbs** [comment]
For items with no expiration dates (Undefined) there is no icons even for expired items, please check it out:

![Image](https://github.com/user-attachments/assets/431e505b-1697-46d6-aad9-1bd7873118d8)

@fjborquez

**Comment by Norbbs** [comment]
for Undefined products (without expiration date), the current date displays and it shouldn't.

We expect this doesn't display because the expiration date was not set.

![Image](https://github.com/user-attachments/assets/156b719c-3cfe-4259-9315-92aa88419711)

@fjborquez

**Comment by fjborquez** [comment]
El problema con los iconos es que no existen en material design.
https://www.angularjswiki.com/angular/angular-material-icons-list-mat-icon-list/ puedes buscar iconos allí

**Comment by Norbbs** [comment]
Ok,
Para los items de inventario sin fecha de expiración (undefined):

![Image](https://github.com/user-attachments/assets/bb62392c-0639-478a-9875-ce92a89b4b9e)

Para los items vencidos (expired):

![Image](https://github.com/user-attachments/assets/06cc3406-3dfb-45f6-b80c-69de58237c18)


Se podrán agregar colores?
Fresh -> Verde
Approaching expiry -> Amarillo
Expired -> Rojo
Undefined -> en negro (así como está)
