### ISSUE TITLE
Inventory Test Results Issues

### ISSUE THREAD

**Issue by Norbbs** [fjborquez/katara#53]
- [x] Fix house's city (User wants to create or update a house, select the city (santiago, viña or concepcion) then you visualize Iquque or Arica.
- [x] Visualiza all cities of chile in the selector city house
- [x] Allow create users without nutritional profile
- [ ] If nutritional profile table has data and then user clicks on "create" button" allow create nutrtional profile items without "add product category" button
- [x] Add "Remove item" button in the nutritional profile section
- [x] Order ASC the list of categories (selector) in the nutritional profile section.
- [x] Add a counter auto increment column (#)

**Comment by Norbbs** [comment]
@fjborquez

**Comment by Norbbs** [comment]
Check katara #57 too @fjborquez

**Comment by fjborquez** [comment]
Add a counter auto increment column (#)  where? @Norbbs

**Comment by fjborquez** [comment]
If nutritional profile table has data and then user clicks on "create" button" allow create nutrtional profile items without "add product category" button:
El botón está para que de los selectores pasen a la tabla, pero la tabla en si no tiene datos. ¿Cómo proceder?

**Comment by Norbbs** [comment]
@fjborquez algo está pasando en las fechas de compra que no coinciden con las fechas de las tablas, en el front parece que les resta un día...

Usando como referencia la casa de "Las Vegas" de Xtina tenemos lo siguiente:

![Image](https://github.com/user-attachments/assets/a3f55480-d2b8-4d78-b1f0-2f7678fbac16)

pero en base de datos se mantienen correctas:

![Image](https://github.com/user-attachments/assets/22a42915-6142-4f3f-979f-914c1b62d26c)
