### ISSUE TITLE
Create user profile with nutritional restriction list

### ISSUE THREAD

**Issue by fjborquez** [fjborquez/katara#6]
**As a** data owner
**I want to** create user profiles with nutritional restrictions
**So that** can create recommendations

### Scope
> 1. User profile
> 2. Nutritional restriction list

### Out of scope
> 1. User creation
> 2. Person creation

### Result
The user must have his user profile with nutritional restrictions

**Comment by Norbbs** [comment]
Change "register" text button after "nutritional profile edition to "update"

**Comment by fjborquez** [comment]
Done!
