### ISSUE TITLE
Product Quantity Increment to Use Whole Numbers Instead of Decimal Increments

### ISSUE THREAD

**Issue by Norbbs** [fjborquez/katara#97]
**As a** user managing inventory
**I want to** adjust the product quantity in whole number increments
**So that** I can quickly and accurately add or remove larger quantities of products without frustration.

### Description
The "Product Quantity" component in the user interface currently increases by 0.01 with each adjustment, which is inefficient for users who need to add larger quantities of products. According to our business requirements, the quantity should increase in increments of 1 to provide a better user experience and facilitate quicker adjustments when adding product quantities.

![Image](https://github.com/user-attachments/assets/8681e01c-58ca-429c-8efe-777af73ddb44)

### Scope

1. When the user clicks the "^" button on the "Product Quantity" component, the quantity should increase by 1.
2. When the user clicks the "v" button, the quantity should decrease by 1.
3. The quantity field should reflect these changes immediately for enhanced user feedback.

### Impact
Users may become frustrated with the inability to adjust quantities accurately, leading to potential errors and delays in inventory updates.

**Comment by Norbbs** [comment]
@fjborquez Hay que hacer un pequeño arreglo acá con el componente:

1. La primera vez que intento incrementar el numero, lo hace por 0,01

![Image](https://github.com/user-attachments/assets/7e840052-1b3e-4761-b503-8ddf424c223f)

2. Después si lo hace bien..

![Image](https://github.com/user-attachments/assets/f19fc37c-2e58-497e-931c-d5b5c53c5f0f)

**Comment by fjborquez** [comment]
done
